name: flutter_secure_storage
repository: https://github.com/mogol/flutter_secure_storage

packages:
  - flutter_secure_storage
  - flutter_secure_storage/example
  - flutter_secure_storage_linux
  - flutter_secure_storage_macos
  - flutter_secure_storage_platform_interface
  - flutter_secure_storage_web
  - flutter_secure_storage_windows
  - flutter_secure_storage_windows/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: true

  bootstrap:
    usePubspecOverrides: true
